version: "3.3"
services:
  mongo:
    image: mongo
    ports:
      - "27027:27017"

  redis:
    image: redis
    ports:
      - '4001:6379'

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
